version: "2"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - private
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - private

  barcelocorona:
    image: barcelocorona:0.0.3
    networks:
      - private
    depends_on:
      - influxdb

networks:
  private:
    driver: bridge